export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED'
}

export enum AppointmentType {
  HAIRCUT = 'HAIRCUT',
  BEARD_TRIM = 'BEARD_TRIM',
  HAIRCUT_AND_BEARD = 'HAIRCUT_AND_BEARD',
  SHAVE = 'SHAVE',
  STYLE = 'STYLE',
  COLOR = 'COLOR',
  TREATMENT = 'TREATMENT',
  CONSULTATION = 'CONSULTATION'
}

export enum CancellationReason {
  CLIENT_REQUEST = 'CLIENT_REQUEST',
  BARBER_UNAVAILABLE = 'BARBER_UNAVAILABLE',
  SHOP_CLOSED = 'SHOP_CLOSED',
  EMERGENCY = 'EMERGENCY',
  WEATHER = 'WEATHER',
  OTHER = 'OTHER'
}

export enum RescheduleReason {
  CLIENT_REQUEST = 'CLIENT_REQUEST',
  BARBER_EMERGENCY = 'BARBER_EMERGENCY',
  SHOP_MAINTENANCE = 'SHOP_MAINTENANCE',
  DOUBLE_BOOKING = 'DOUBLE_BOOKING',
  OTHER = 'OTHER'
}