export enum PaymentType {
  BOOKING_PAYMENT = 'BOOKING_PAYMENT',
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  COMMISSION_PAYMENT = 'COMMISSION_PAYMENT',
  SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT',
  REFUND = 'REFUND',
}