export enum ServiceCategory {
  HAIRCUT = 'HAIRCUT',
  BEARD = 'BEARD',
  SHAVE = 'SHAVE',
  STYLE = 'STYLE',
  COLOR = 'COLOR',
  TREATMENT = 'TREATMENT',
  PACKAGE = 'PACKAGE',
  CONSULTATION = 'CONSULTATION'
}

export enum ServiceStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE'
}